root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"

send_interrupt = true
# Rerun binary or not
rerun = false
# Delay after each execution
rerun_delay = 500

delay = 1000
kill_delay = 10
